### ISSUE TITLE
Screenshot for each module?

### ISSUE THREAD

**Issue by tuxun** [CityScope/CS_CityScopeJS_Tables#2]
![capture d ecran de 2018-11-16 02-51-06](https://user-images.githubusercontent.com/3581513/48592867-b2b72980-e94a-11e8-8971-cdb2ce081b0d.png)
here is a WalkJS screenshot, could it be added to the readme file? Can we do the same for MobCho? goal is to understand graphically what the apps make us able to visualize and how, before we start to test them.
PS: if someone have a gif of this moving with an animated walkJS table, it would be better (here its the actual CityScopeJS table, not the CityScopeJS_WalkJS one)

**Comment by RELNO** [comment]
Should definitely get to properly doc this [and the mocho table]. Would be great to see a PR with your readme and gifs/screenshots

**Comment by RELNO** [comment]
Sure, but any form of documentation would be a good starting point - thanks

**Comment by tuxun** [comment]
let see... 
![capture d ecran de 2018-11-18 04-03-45](https://user-images.githubusercontent.com/3581513/48668160-3148ce00-eae7-11e8-82db-43fed34ffbb1.png)
on day someone will need to take these picture and put them in the repo, i guess

**Comment by RELNO** [comment]
Great thanks for putting this together -- we might end up replacing these with screens from the lab's table but for now it's great
